title: "[General] "
labels: ["General Introduction"]
body:
  - type: input
    id: Author
    attributes:
      label: Author
    validations:
      required: true
  - type: textarea
    id: Summary
    attributes:
      label: Summary
      description: "Summarize the core content of your proposal in two or three sentences. Briefly explain what you're proposing so it's easy to understand at a glance."
    validations:
      required: true