title: "[General] "
labels: ["General Introduction"]
body:
  - type: input
    id: Author
    attributes:
      label: Author
    validations:
      required: true
  - type: textarea
    id: Summary
    attributes:
      label: Summary
      description: "Summarize the core content of your proposal in two or three sentences. Briefly explain what you're proposing so it's easy to understand at a glance."
    validations:
      required: true
  - type: textarea
    id: Background & Motivation
    attributes:
      label: Background & Motivation
      description: "Describe in detail the background to your proposal, the problem you identified, and why improvements are needed."
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Proposal Details
  - type: textarea
    id: Specification
    attributes:
      label: Specification
      description: "Describe a detailed, step-by-step plan for implementing or executing the proposal."
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        This is text that will show up in the template!
  - type: textarea
    id: improvements
    attributes:
      label: Top 3 improvements
      description: "What are the top 3 improvements we could make to this project?"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_