exports.AGENDA_INDEX_CREATED_TIMESTAMP = 0;
exports.AGENDA_INDEX_NOTICE_END_TIMESTAMP = 1;
exports.AGENDA_INDEX_VOTING_PERIOD_IN_SECONDS = 2;
exports.AGENDA_INDEX_VOTING_STARTED_TIMESTAMP = 3;
exports.AGENDA_INDEX_VOTING_END_TIMESTAMP = 4;
exports.AGENDA_INDEX_EXECUTABLE_LIMIT_TIMESTAMP = 5;
exports.AGENDA_INDEX_EXECUTED_TIMESTAMP = 6;
exports.AGENDA_INDEX_COUNTING_YES = 7;
exports.AGENDA_INDEX_COUNTING_NO = 8;
exports.AGENDA_INDEX_COUNTING_ABSTAIN = 9;
exports.AGENDA_INDEX_STATUS = 10;
exports.AGENDA_INDEX_RESULT = 11;
exports.AGENDA_INDEX_EXECUTED = 13;

exports.AGENDA_STATUS_NONE = 0;
exports.AGENDA_STATUS_NOTICE = 1;
exports.AGENDA_STATUS_VOTING = 2;
exports.AGENDA_STATUS_WAITING_EXEC = 3;
exports.AGENDA_STATUS_EXECUTED = 4;
exports.AGENDA_STATUS_ENDED = 5;

exports.VOTE_ABSTAIN = 0;
exports.VOTE_YES = 1;
exports.VOTE_NO = 2;

exports.AGENDA_RESULT_PENDING = 0;
exports.AGENDA_RESULT_ACCEPTED = 1;
exports.AGENDA_RESULT_REJECTED = 2;
exports.AGENDA_RESULT_DISMISSED = 3;

exports.VOTER_INFO_ISVOTER = 0;
exports.VOTER_INFO_HAS_VOTED = 1;
exports.VOTER_INFO_VOTE = 2;

exports.CANDIDATE_INFO_INDEX_CANDIDATE_CONTRACT = 0;
exports.CANDIDATE_INFO_INDEX_MEMBER_JOINED_TIME = 1;
exports.CANDIDATE_INFO_INDEX_MEMBER_INDEX = 2;
exports.CANDIDATE_INFO_INDEX_REWARD_PERIOD = 3;
